- platform: template
  sensors:
    google_ping_time_avg:
        friendly_name: "google ping time avg"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.google', 'round_trip_time_avg') }}"
    google_ping_time_max:
        friendly_name: "google ping time max"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.google', 'round_trip_time_max') }}"
    google_ping_time_min:
        friendly_name: "google ping time min"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.google', 'round_trip_time_min') }}"

- platform: template
  sensors:
    gateway_ping_time_avg:
        friendly_name: "gateway ping time avg"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.gateway', 'round_trip_time_avg') }}"
    gateway_ping_time_max:
        friendly_name: "gateway ping time max"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.gateway', 'round_trip_time_max') }}"
    gateway_ping_time_min:
        friendly_name: "gateway ping time min"
        unit_of_measurement: "ms"
        value_template: "{{ state_attr('binary_sensor.gateway', 'round_trip_time_min') }}"