- platform: integration
  source: sensor.k1_coffeemachine_power
  name: Coffee Machine Power Usage
  round: 2
  method: left

- platform: integration
  source: sensor.master_ac_power
  name: Master Aircon Power Usage
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.6920ha_power
  name: Office Socket Power Usage
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.tvunit_power
  name: TV Unit Power Usage
  unit_prefix: k
  round: 2