#monitoring the PI
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: memory_use_percent
    - type: processor_temperature